# Generated by Django 3.1.7 on 2021-02-27 21:58

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to=myapp.models.userDirectoryPath),
        ),
    ]
