# Generated by Django 3.1.7 on 2021-02-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210227_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='student',
            new_name='user',
        ),
    ]
