# Generated by Django 3.1.7 on 2021-02-28 01:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20210227_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='user',
            field=models.ForeignKey(default=models.ForeignKey(default=myapp.models.getRequestUser, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=myapp.models.userDirectoryPath)),
                ('startDate', models.DateField(default=datetime.datetime.now)),
                ('endDate', models.DateField(default=datetime.datetime.now)),
                ('artistStatement', models.TextField()),
                ('user', models.ForeignKey(default=models.ForeignKey(default=myapp.models.getRequestUser, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibit',
            field=models.ForeignKey(default=myapp.models.getUserExhibit, on_delete=django.db.models.deletion.PROTECT, to='myapp.exhibit'),
        ),
    ]
