# Generated by Django 3.1.7 on 2021-02-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210228_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='user',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.artist'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.artist'),
        ),
    ]
