# Generated by Django 3.1.7 on 2021-02-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210228_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='mentor',
        ),
        migrations.AddField(
            model_name='artist',
            name='mentorship',
            field=models.ManyToManyField(related_name='_artist_mentorship_+', to='myapp.Artist'),
        ),
    ]
